export const validationClientErrors = [
  {
    error: "El nombre del contacto debe ser una cadena",
    value: 123,
    field: "nombreContacto",
    title: "Should return 422 if nombreContacto is not a string",
  },
  {
    error: "El nombre del contacto debe tener al menos 3 caracteres",
    value: "Lu",
    field: "nombreContacto",
    title: "Should return 422 if nombreContacto is less than 3 caracters",
  },
  {
    error: "El nombre del contacto no debe exceder los 70 caracteres",
    value: "L".repeat(71),
    field: "nombreContacto",
    title: "Should return 422 if nombreContacto is more than 70 caracters",
  },
  {
    error: "El nombre de la empresa debe ser una cadena",
    value: 123,
    field: "nombreEmpresa",
    title: "Should return 422 if nombreEmpresa is not a string",
  },
  {
    error: "El nombre de la empresa debe tener al menos 3 caracteres",
    value: "In",
    field: "nombreEmpresa",
    title: "Should return 422 if nombreEmpresa is less than 3 caracters",
  },
  {
    error: "El nombre de la empresa no debe exceder los 70 caracteres",
    value: "I".repeat(71),
    field: "nombreEmpresa",
    title: "Should return 422 if nombreEmpresa is more than 70 caracters",
  },
  {
    error: "El teléfono de la empresa debe ser una cadena",
    value: 1_234_567,
    field: "empresaTelefono",
    title: "Should return 422 if empresaTelefono is not a string",
  },
  {
    error: "El teléfono de la empresa debe tener al menos 7 caracteres",
    value: "123456",
    field: "empresaTelefono",
    title: "Should return 422 if empresaTelefono is less than 7 caracters",
  },
  {
    error: "El teléfono de la empresa no debe exceder los 22 caracteres",
    value: "1".repeat(23),
    field: "empresaTelefono",
    title: "Should return 422 if nombreEmpresa is more than 22 caracters",
  },
  {
    error: "El email de la empresa no es válido",
    value: "invalid-email",
    field: "emailEmpresa",
    title: "Should return 422 if emailEmpresa is not a valid email",
  },
  {
    error: "El email de la empresa no debe exceder los 150 caracteres",
    value: "a".repeat(151) + "@gmail.com",
    field: "emailEmpresa",
    title: "Should return 422 if emailEmpresa is more than 150 caracters",
  },
  {
    error: "El email del contacto no es válido",
    value: "invalid-email",
    field: "emailContacto",
    title: "Should return 422 if emailContacto is not a valid email",
  },
  {
    error: "El email del contacto no debe exceder los 150 caracteres",
    value: "a".repeat(151) + "@gmail.com",
    field: "emailContacto",
    title: "Should return 422 if emailContacto is more than 150 caracters",
  },
  {
    error: "El CI/RIF debe ser una cadena",
    value: 12_345_678,
    field: "ciRif",
    title: "Should return 422 if ciRif is not a string",
  },
  {
    error: "El CI/RIF no es válido",
    value: "invalid-ci",
    field: "ciRif",
    title: "Should return 422 if ciRif is not valid",
  },
  {
    error: "El CI/RIF debe tener al menos 6 caracteres",
    value: "V1234",
    field: "ciRif",
    title: "Should return 422 if ciRif is less than 6 caracters",
  },
  {
    error: "El CI/RIF no debe exceder los 11 caracteres",
    value: "V12345678911",
    field: "ciRif",
    title: "Should return 422 if ciRif is more than 11 caracters",
  },
  {
    error: "La dirección fiscal debe ser una cadena",
    value: 12_345,
    field: "direccionFiscal",
    title: "Should return 422 if direccionFiscal is not a string",
  },
  {
    error: "La dirección fiscal debe tener al menos 10 caracteres",
    value: "Short St",
    field: "direccionFiscal",
    title: "Should return 422 if ciRif is less than 10 caracters",
  },
  {
    error: "La dirección fiscal no debe exceder los 350 caracteres",
    value: "A".repeat(351),
    field: "direccionFiscal",
    title: "Should return 422 if ciRif is more than 350 caracters",
  },
];
